services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://api.tracksport.socratesunicordoba.co
    ports:
      - "5173:80"
    restart: unless-stopped
    volumes:
      # Opcional: para logs de nginx
      - nginx_logs:/var/log/nginx
    networks:
      tracksport-network:
        ipv4_address: 172.20.10.12

networks:
  tracksport-network:
    external: true

volumes:
  nginx_logs:
